#!/bin/bash
set -euf -o pipefail

selfdir="$(dirname "$0")"

if [[ "${1:-}" == "--build" ]]; then shift; dobuild=y; fi
if [[ -n "${dobuild:-}" || -z "$(docker image ls -q pycheck)" ]]; then
  ( cd "$selfdir"; docker build -t pycheck .; )
fi

docker run --rm \
  --volume "$PWD:/prj" \
  --volume "$HOME/.cache/pycheck:/cache" \
  --env XDG_CACHE_HOME=/cache \
  --env MYPY_CACHE_DIR=/cache/mypy \
  --env PYTHONDONTWRITEBYTECODE=1 \
  --workdir /prj \
  pycheck python -u /check.py "$@"
